### ISSUE TITLE
Centos 1.4 distro

### ISSUE THREAD

**Issue by BongoEADGC6** [logstash-plugins/logstash-output-nagios_nsca#2]
Good morning,

I figured out a bug that is located in the nagios_nsca.rb output file for the CentOS repo install
    [logstash-1.4]
    name=logstash repository for 1.4.x packages
    baseurl=http://packages.elasticsearch.org/logstash/1.4/centos
    gpgcheck=1
    gpgkey=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    enabled=1

in the original file that was installed it reads as such:
    # build the command
    # syntax: echo '<server>!<nagios_service>!<status>!<text>'  | \
    #           /usr/sbin/send_nsca -H <nagios_host> -d '!' -c <nsca_config>"

```
cmd = [@send_nsca_bin, "-H", "@host", "-p", "@port", "-d", "~"]
cmd = cmd + ["-c", @send_nsca_config]  if @send_nsca_config
message = "#{nagios_host}~#{nagios_service}~#{status}~#{msg}"
```

As you can see, "@host" and "@port" are a problem since they are supposed to call a variable but instead act as a string. 

It should instead read:
cmd = [@send_nsca_bin, "-H", @host, "-p", @port, "-d", "~"]

This allows functionality to the output.

**Comment by purbon** [comment]
This is fixed in the codebase. closing this issue as is not like this is the codebase anymore.
