### ISSUE TITLE
after applying the 2.0.3 error on start

### ISSUE THREAD

**Issue by nnebojsa** [logstash-plugins/logstash-output-nagios_nsca#9]
After applying the 2.0.3 version with bin/plugin update logstash-output-nagios_nsca, run into error:

logstash-output-nagios (2.0.2)
logstash-output-nagios_nsca (2.0.3)
logstash-output-null (2.0.2)
logstash-output-opentsdb (2.0.2)
logstash-output-pagerduty (2.0.2)
logstash-output-pipe (2.0.2)
logstash-output-rabbitmq (3.0.5)
logstash-output-redis (2.0.2)
logstash-output-s3 (2.0.3)
logstash-output-sns (3.0.2)
logstash-output-sqs (2.0.2)
logstash-output-statsd (2.0.4)
logstash-output-stdout (2.0.2)
logstash-output-tcp (2.0.2)
logstash-output-udp (2.0.2)
logstash-output-xmpp (2.0.2)
logstash-output-zeromq (2.0.2)
logstash-patterns-core (2.0.2)
[root@dbdev ~]# /opt/logstash/bin/logstash agent -f /etc/logstash/conf.d/shipper.conf --debug -v -l /tmp/logfile.log -vv
RuntimeError: Logstash expects concurrent-ruby version 0.9.1 and version 0.9.2 is installed, please verify this patch: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches/silence_concurrent_ruby_warning.rb
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches/silence_concurrent_ruby_warning.rb:53
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches.rb:6
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/environment.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/lib/bootstrap/environment.rb:48
[root@dbdev ~]# 

OS:
lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.4 (Final)
Release:    6.4
Codename:   Final

java:
java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

RPM:
rpm -qi logstash-2.0.0-1.noarch 
Name        : logstash                     Relocations: / 
Version     : 2.0.0                             Vendor: Elasticsearch
Release     : 1                             Build Date: Tue 27 Oct 2015 07:48:24 PM CET
Install Date: Wed 25 Nov 2015 11:04:57 AM CET      Build Host: slave12.build.ci.hetz.es.io
Group       : default                       Source RPM: logstash-2.0.0-1.src.rpm
Size        : 136366484                        License: ASL 2.0
Signature   : RSA/SHA1, Wed 28 Oct 2015 03:47:40 PM CET, Key ID d27d666cd88e42b4
Packager    : jenkins@slave12.build.ci.hetz.es.io
URL         : http://www.elasticsearch.org/overview/logstash/
Summary     : An extensible logging pipeline
Description :
An extensible logging pipeline

---

Workaround for me:
in logstash home:
echo "gem 'concurrent-ruby', '0.9.1'" >> Gemfile

and change everywere in lock file 'concurrent-ruby' to 0.9.1, after them:
bin/plugin install --no-verify

Now its work with the 2.0.3. plugin version.

**Comment by jsvd** [comment]
I can't replicate this in recent logstash 6.x , please reopen if you still see this error
